import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ThemeProvider defaultTheme="light" attribute="class"> */}
      <body className={inter.className}>
        <main className="dark:bg-gray-800 w-full">
          <Navbar />
          <div>{children}</div>
          <Footer />
        </main>
      </body>
      {/* </ThemeProvider> */}
    </html>
  );
}
